# listas 2

lista=["manzana","banana","cereza","banana","naranja","kiwi","melon","mango"]

lista.remove("banana")  # elimina el elemento especificado
print("remove:",lista)  

lista.pop()             # elimina el ultimo elemento
print("pop:",lista)

lista.pop(1)            # elimina el elemento en la posicion especificada
print("pop(1):",lista)

del lista[0]          # elimina el elemento en la posicion especificada
print("del lista[0]:",lista)

